language: 
    python

sudo:
    - "true"

python:
    - "2.7"

install:
    - ls
    - pip install -r requirements.txt
    - git clone https://github.com/DMTF/Redfish-Mockup-Server.git
    - mkdir logs
    - mkdir config
    - cp ./config.ini config
    - wget http://www.dmtf.org/sites/default/files/standards/documents/DSP8010_2016.3.zip
    - unzip -j "DSP8010_2016.3.zip" "DSP8010_2016.3/metadata/*" -d "./metadata"
    - wget http://www.dmtf.org/sites/default/files/standards/documents/DSP2043_1.1.0.zip
    - unzip ./DSP2043_1.1.0.zip ./

script:
    - ls
    - python3 Redfish-Mockup-Server/redfishMockupServer.py & sleep 10
    - python Redfish-Service-Validator/RedfishServiceValidator.py
